use_frameworks!

platform :ios, '11.0'

target 'FWPlayer_Example' do
  pod 'FWPlayer', :path => '../'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  # pod 'RxDataSources'
  pod 'NSObject+Rx'

  pod 'SideMenuSwift'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'Then'
  pod 'DarkModeKit'
  
  pod 'Alamofire'
  pod 'Moya'
  pod 'HandyJSON'
  pod 'SwiftyJSON'
  
  pod 'TYCyclePagerView'
  pod 'SwiftyColor'
  pod 'SwiftMessages'
  
  # pod 'MJRefresh'
  # pod 'TYPagerController'
  # pod 'SKPhotoBrowser'
  # pod '1PasswordExtension'
  # pod 'SkeletonView'

  target 'FWPlayer_Tests' do
    inherit! :search_paths

    
  end
end
